" General Setup

" let's just get this right out of the way, we're gonna be...
set nocompatible

" UI Settings
syntax enable
set nowrap
set listchars=tab:›\ ,nbsp:_,trail:·
set list

" General file settings
set encoding=utf-8
set fileencoding=utf-8
set fileformat=unix
set smartindent
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

set incsearch
set ignorecase
set smartcase
set wildignorecase
set path+=**
set wildmenu
set wildmode=longest,list,full

" Plugins
call plug#begin('~/.local/share/nvim/plugged')
Plug 'PotatoesMaster/i3-vim-syntax'
Plug 'Shougo/vimproc', {'do' : 'make'}
Plug 'chr4/nginx.vim'
Plug 'chrisbra/csv.vim', {'for' : 'csv'}
Plug 'chrisbra/Colorizer'
Plug 'dhruvasagar/vim-table-mode'
Plug 'editorconfig/editorconfig-vim'
Plug 'fatih/vim-go', {'for' : 'go'}
Plug 'junegunn/fzf'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-user'
Plug 'leafgarland/typescript-vim', {'for' : 'typescript'}
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/argtextobj.vim'
Plug 'vim-scripts/camelcasemotion'
Plug 'vito-c/jq.vim'
call plug#end()

" Custom highlighting
hi Comment ctermfg=Black
hi NonText ctermfg=Black

" Filetype-specific configuration and autocommands

" spellcheck markdown files and git commit messages
au FileType markdown set spell tw=80 colorcolumn=81 nosmartindent
au FileType gitcommit set spell

" when writing java code, use javacomplete as the omnifunc and set spacing
"au FileType java setlocal omnifunc=javacomplete#Complete
au FileType java setlocal errorformat=[ERROR]\ %f:[%l\\,%v]\ %m

" git-config(1) uses tabs, so we should too
au FileType gitconfig setlocal noexpandtab

" crontab must be edited in place, which is not done by default
" see https://stackoverflow.com/a/21194148
autocmd FileType crontab setlocal nowritebackup

" colorizer settings
let g:colorizer_auto_filetype=''

" vim-go settings
let g:go_metalinter_autosave = 1

" double-Esc clears last search
nnoremap <silent> <Esc><Esc> <Esc>:let @/=""<CR><Esc>

" make it easier to type ex commands
noremap ; :

" open FZF with Ctrl-P
nmap <C-p> :FZF<CR>

" easier navigation
"
" this is hacky but some terminals send <BS> instead of <C-h> when ctrl-h is
" pressed. since i don't really use <BS> in normal mode, this seems like a
" reasonable thing for it to do.
nmap <BS> <C-w>h
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l
nmap <C-q> <C-w>q

