set nocompatible
syntax enable
set nowrap
set listchars=tab:›\ ,nbsp:_,trail:·
set list
set encoding=utf-8
set fileencoding=utf-8
set fileformat=unix
set smartindent
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set incsearch
set ignorecase
set smartcase
set wildignorecase
set path+=**
set wildmenu
set wildmode=longest,list,full

call plug#begin('~/.local/share/nvim/plugged')
Plug 'PotatoesMaster/i3-vim-syntax'
Plug 'chr4/nginx.vim'
Plug 'chrisbra/csv.vim', {'for' : 'csv'}
Plug 'chrisbra/Colorizer'
Plug 'dhruvasagar/vim-table-mode'
Plug 'editorconfig/editorconfig-vim'
Plug 'fatih/vim-go', {'for' : 'go'}
Plug 'junegunn/fzf'
Plug 'kana/vim-textobj-entire'
Plug 'kana/vim-textobj-user'
Plug 'leafgarland/typescript-vim', {'for' : 'typescript'}
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/argtextobj.vim'
Plug 'vim-scripts/camelcasemotion'
Plug 'vito-c/jq.vim'
call plug#end()

hi! Comment      ctermfg=DarkBlue cterm=Bold
hi! NonText      ctermfg=DarkBlue
hi! Folded       ctermfg=DarkBlue ctermbg=NONE
hi! LineNr       ctermfg=DarkBlue
hi! StatusLine   cterm=bold ctermfg=Blue ctermbg=NONE
hi! StatusLineNC cterm=NONE ctermfg=Black ctermbg=NONE
hi! VertSplit    cterm=NONE ctermfg=Black ctermbg=NONE

au FileType markdown setlocal spell tw=80 colorcolumn=81 nosmartindent
au FileType gitcommit setlocal spell
au FileType java setlocal errorformat=[ERROR]\ %f:[%l\\,%v]\ %m
au FileType gitconfig setlocal noexpandtab
au FileType crontab setlocal nowritebackup

let g:colorizer_auto_filetype=''
let g:go_metalinter_autosave = 1

nnoremap <silent> <Esc><Esc> <Esc>:let @/=""<CR><Esc>
noremap ; :
nmap <C-p> :FZF<CR>
