---
- name: Install VLC
  homebrew_cask:
    name: vlc
    state: present
  when: ansible_pkg_mgr == "homebrew"
- apt:
    name: vlc
    state: present
  when: ansible_pkg_mgr == "apt"
  become: yes
- pacman:
    name: vlc
    state: present
  when: ansible_pkg_mgr == "pacman"
  become: yes
