---
- homebrew:
    name: go
    state: present
  when: ansible_facts['system'] == "Darwin"
- unarchive:
    src: https://dl.google.com/go/go1.10.3.linux-amd64.tar.gz
    dest: /usr/local
  become: true
  when: ansible_facts['system'] == "Linux"

