---
- name: Playbook to manage Debian configuration
  hosts: localhost
  vars:
    sudoers_group: sudo
    gpg_pinentry_program: /usr/bin/pinentry
  vars_files:
    - vars.yml
  roles:
    - alacritty
    - i3
    - passwordless-sudo
    - apt
    - zsh
    - tmux
    - lynx
    - python
    - golang
    - neovim
    - jq
    - aws
    - postgresql-client
    - java
    - google-java-format
    - ngrok
    - maven
    - fzf
    - ripgrep
    - gpg
    - mutt
    - ffmpeg
    #- handbrake
    - vlc
    - gimp
    - nodejs
    - tex
    - git
    - mitmproxy
    - ctags
    - clitools
    - virtualbox
    - wireshark
    - transmission
    - etcher
    - slack
    - spotify
    - docker
    - yubikey
    - newsboat
    - bin
    - irssi
    - ssh
    - firefox
    - xorg
    - urxvt
