---
- hosts: 127.0.0.1
  connection: local
  roles:
    - i3
    - urxvt
    - tmux
    - firefox
    - lynx
    - neovim
#    - sysadmin
#    - gpg
#    - pass
#    - comm
#    - aws
#    - docker
#    - finance
#    - golang
#    - java
#    - nodejs
#    - tex
#    - media
#    - minecraft
#    - dropbox
