---
- hosts: 127.0.0.1
  connection: local
  roles:
    - zsh
    - localuser
    - apt
    - xorg
    - i3
    - urxvt
    - tmux
    - firefox
    - lynx
    - pip
    - golang
    - neovim
    - curl
    - ssh-server
#    - sysadmin
#    - gpg
#    - pass
#    - comm
#    - aws
#    - docker
#    - finance
#    - java
#    - nodejs
#    - tex
#    - media
#    - minecraft
#    - dropbox
