---
- name: Playbook to manage macOS configuration
  hosts: localhost
  vars:
    sudoers_group: admin
    gpg_pinentry_program: /usr/local/bin/pinentry-mac
    git_credential_helper: osxkeychain
  vars_files:
    - vars.yml
  roles:
    - passwordless-sudo
    - name: zsh
      tags: ce
    - name: tmux
      tags: ce
    - lynx
    - python
    - golang
    - name: neovim
      tags: ce
    - jq
    - aws
    - postgresql-client
    - java
    - google-java-format
    - ngrok
    - maven
    - fzf
    - ripgrep
    - gpg
    - mutt
    - ffmpeg
    - handbrake
    - vlc
    - imageoptim
    - gimp
    - licecap
    - appcleaner
    - nodejs
    - tex
    - git
    - mitmproxy
    - ctags
    - clitools
    - theunarchiver
    - virtualbox
    - wireshark
    - transmission
    - etcher
    - viscosity
    - slack
    - spotify
    - docker
    - yubikey
    - newsboat
    - bin
    - irssi
    - ssh
    - iterm2
    # - firefox
    - name: finder
      tags: de
    - minecraft
    - gnucash
    - name: alacritty
      tags: ce
# TODO
#k8s
#mitmproxy
#pivman
#s3cmd
#slack-term
#travis
