---
- hosts: 127.0.0.1
  connection: local
  roles:
    - desktop-env
    - urxvt
#    - terminal
#    - dotfiles
#    - sysadmin
#    - gpg
#    - pass
#    - browser
#    - comm
#    - aws
#    - docker
#    - finance
#    - golang
#    - java
#    - nodejs
#    - tex
#    - media
#    - minecraft
#    - dropbox
