---
- name: Passwordless sudo
  hosts: all
  become: yes
  roles:
    - passwordless-sudo
- name: SSH server
  hosts: all
  roles:
    - ssh-server
- name: Workstation OS and user
  hosts: workstations
  roles:
    - zsh
    - localuser
    - role: apt
      when: ansible_facts['os_family'] == 'Debian'
- name: Linux desktop environment
  hosts: workstations
  roles:
    - role: xorg
      when: ansible_facts['system'] == 'Linux'
    - role: i3
      when: ansible_facts['system'] == 'Linux'
    - role: urxvt
      when: ansible_facts['system'] == 'Linux'
- name: GUI programs
  hosts: workstations
  roles:
    - firefox
- name: Development tools
  hosts: workstations
  roles:
    - tmux
    - lynx
    - pip
    - golang
    - neovim
    - curl
    - docker
    - shellcheck
    - jq
    - aws
    - postgresql-client
    - java
    - ngrok
    - maven
    - fzf
    - ripgrep
- name: Configure NFS share
  hosts: dataservers
  become: yes
  roles:
    - dataserver

# TODO
#comm
#gpg
#iterm2
#nodejs
#pass
#sysadmin
