---
- package:
    name: irssi
    state: present
  become: "{{'no' if ansible_pkg_mgr == 'homebrew' else 'yes'}}"
- file:
    path: ~/.irssi
    state: directory
    mode: 0700
- template:
    src: config
    dest: ~/.irssi/config
    mode: 0600
