---
- name: Install Xorg
  become: true
  apt: name=xorg state=present
- name: Install Xdefaults
  template: src=Xdefaults dest=~/.Xdefaults
- name: Install Fira Code
  become: true
  apt: name=fonts-firacode
