---
- name: Use https for apt repositories
  become: true
  apt:
    name: apt-transport-https
    state: present
- name: Enable sid contrib repository
  become: true
  apt_repository:
    repo: deb https://ftp.us.debian.org/debian/ sid main contrib
    state: present
    update_cache: yes
