---
- homebrew_cask:
    name: mactex
    state: present
  when: ansible_pkg_mgr == "homebrew"
- apt:
    name: texlive-full
    state: present
  when: ansible_pkg_mgr == "apt"
  become: yes
- pacman:
    name: texlive-most
    state: present
  when: ansible_pkg_mgr == "pacman"
  become: yes
