---
- homebrew: name=lynx state=present
  when: ansible_facts['system'] == "Darwin"
- apt: name=lynx state=present
  become: true
  when: ansible_facts['system'] == "Linux"
- copy: src=lynxrc dest=~/.lynxrc
- copy: src=lynx.cfg dest=~/.lynx.cfg
- copy: src=lynx.lss dest=~/.lynx.lss
