---
- homebrew: name=lynx state=present
  when: ansible_facts['system'] == "Darwin"
- apt: name=lynx state=present
  become: true
  when: ansible_facts['system'] == "Linux"
- copy:
    src: '{{item}}'
    dest: '~/.{{item}}'
  loop:
    - lynxrc
    - lynx.cfg
    - lynx.lss
