---
- package:
    name: lynx
    state: present
  become: "{{'no' if ansible_pkg_mgr == 'homebrew' else 'yes'}}"
- copy:
    src: '{{item}}'
    dest: '~/.{{item}}'
  loop:
    - lynxrc
    - lynx.cfg
    - lynx.lss
