---
- name: Install OpenJDK
  pkgng:
    name: openjdk8-jre
    state: present
- name: Create srv directory
  file:
    path: /srv
    state: directory
    owner: root
    group: wheel
    mode: 0755
- name: Create minecraft group
  group:
    gid: 25565
    name: minecraft
    state: present
- name: Create minecraft user
  user:
    uid: 25565
    name: minecraft
    state: present
    group: minecraft
    create_home: no
    comment: Minecraft server user
    home: /srv/minecraft
    password: '*'
    shell: /usr/sbin/nologin
- name: Create minecraft server directory
  file:
    path: /srv/minecraft
    state: directory
    owner: minecraft
    group: minecraft
    mode: 0755
- name: Download minecraft server
  get_url:
    url: https://launcher.mojang.com/v1/objects/3737db93722a9e39eeada7c27e7aca28b144ffa7/server.jar
    checksum: sha256:ffd3aa2c25c5ba68a706b59f2abdc69ac1748e115ca9d3b47941e197736f088e
    dest: /srv/minecraft/minecraft_server.jar
    owner: minecraft
    group: minecraft
    mode: 0755
- name: Add minecraft RC script
  copy:
    src: minecraft_rc.sh
    dest: /usr/local/etc/rc.d/minecraft
    mode: 0555
    owner: root
    group: wheel
- name: Enable minecraft server
  sysrc:
    name: minecraft_enable
    value: "YES"
- name: Configure minecraft user
  sysrc:
    name: minecraft_user
    value: minecraft
- name: Set minecraft directory
  sysrc:
    name: minecraft_chdir
    value: /srv/minecraft
- name: Set minecraft server path
  sysrc:
    name: minecraft_path
    value: /srv/minecraft/minecraft_server.jar
- name: Copy minecraft server properties
  register: properties
  template:
    src: server.properties.j2
    dest: /srv/minecraft/server.properties
    owner: minecraft
    group: minecraft
    mode: 0644
- name: Agree to EULA
  register: eula
  copy:
    src: eula.txt
    dest: /srv/minecraft/eula.txt
    owner: minecraft
    group: minecraft
    mode: 0644
- name: Whitelist
  register: whitelist
  template:
    src: whitelist.json.j2
    dest: /srv/minecraft/whitelist.json
    owner: minecraft
    group: minecraft
    mode: 0644
- name: Ops
  register: ops
  template:
    src: ops.json.j2
    dest: /srv/minecraft/ops.json
    owner: minecraft
    group: minecraft
    mode: 0644
- name: Restart Minecraft server
  when: properties.changed or eula.changed or whitelist.changed or ops.changed
  service:
    name: minecraft
    state: restarted
