---
- name: Install node and yarn
  homebrew:
    name:
      - node
      - yarn
    state: present
  when: ansible_pkg_mgr == "homebrew"
- apt:
    name: node
    state: present
  when: ansible_pkg_mgr == "apt"
  become: true
