---
- name: Install nvm
  homebrew:
    name: nvm
    state: present
- name: Install node stable
  shell: nvm install stable
- name: Use node stable
  shell: nvm use stable
- name: Make node stable the default node
  shell: nvm alias default stable
- name: Install yarn
  homebrew:
    name: yarn
    state: present
