---
- name: Install node and yarn
  homebrew:
    name:
      - node
      - yarn
    state: present
  when: ansible_pkg_mgr == "homebrew"
- apt:
    name: nodejs
    state: present
  when: ansible_pkg_mgr == "apt"
  become: true
- pacman:
    name:
    - nodejs
    - yarn
    - npm
    state: present
  when: ansible_pkg_mgr == "pacman"
  become: true
