---
- name: install maven
  become: "{{'no' if ansible_pkg_mgr == 'homebrew' else 'yes'}}"
  package:
    name: maven
    state: present
- name: m2 folder
  file:
    path: ~/.m2
    state: directory
    mode: '700'
- name: settings.xml
  template:
    src: settings.xml
    dest: ~/.m2/settings.xml
    mode: '600'
