---
- homebrew:
    name:
    - python@2
    - python
    state: present
  when: ansible_pkg_mgr == "homebrew"
- apt:
    name:
    - python
    - python3
    state: present
  when: ansible_pkg_mgr == "apt"
- pacman:
    name:
    - python
    - python2
    state: present
  when: ansible_pkg_mgr == "pacman"
- name: check if pip is installed
  command: which pip
  register: pip_task_installed
  changed_when: no
  failed_when: no
- name: download pip installer
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: "/tmp/get-pip.py"
  when: pip_task_installed is defined and
        pip_task_installed.rc is defined and
        pip_task_installed.rc != 0
- name: run installer
  command: "{{ ansible_python_interpreter | default('python') }} /tmp/get-pip.py"
  become: yes
  when: pip_task_installed is defined and
        pip_task_installed.rc is defined and
        pip_task_installed.rc != 0
