---
- pacman:
    name: openssh
    state: present
  become: yes
  when: ansible_pkg_mgr == "pacman"
- file:
    path: ~/.ssh
    state: directory
    mode: 0700
- copy:
    src: authorized_keys
    dest: ~/.ssh/authorized_keys
    mode: 0600
