---
- name: Install awscli
  become: true
  pip:
    name: awscli
    state: present
- name: Create AWS directory
  file:
    path: '~/.aws'
    state: directory
    mode: '700'
- name: Create credentials file
  template:
    src: credentials.j2
    dest: '~/.aws/credentials'
    mode: '600'
