---
# TODO: add --java-completer
- name: PlugInstall
  shell: "nvim --headless +PlugInstall +qall!"
- name: InstallYouCompleteMe
  shell: |
    export PATH=$PATH:/usr/local/go/bin
    cd ~/.local/share/nvim/plugged/YouCompleteMe
    ./install.py --go-completer --java-completer
