---
- name: check for ripgrep
  shell: which rg
  register: rg_check
  changed_when: no
  failed_when: no
- name: ripgrep deb
  become: yes
  when: ansible_pkg_mgr == "apt" and
        rg_check is defined and
        rg_check.rc is defined and
        rg_check.rc != 0
  apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/0.8.1/ripgrep_0.8.1_amd64.deb
- name: ripgrep homebrew
  when: ansible_pkg_mgr == "homebrew" and
        rg_check is defined and
        rg_check.rc is defined and
        rg_check.rc != 0
  homebrew:
    name: ripgrep
    state: present
- pacman:
    name: ripgrep
    state: present
  become: yes
  when: ansible_pkg_mgr == "pacman"
