---
- name: go get fzf
  when: ansible_pkg_mgr != "homebrew"
  shell: GOPATH=~/code PATH=$PATH:/usr/local/go/bin go get -u github.com/junegunn/fzf
  args:
    creates: ~/code/src/github.com/junegunn/fzf
- name: brew fzf
  when: ansible_pkg_mgr == "homebrew"
  homebrew:
    name: fzf
    state: present
