---
- name: Install git and hub
  when: ansible_pkg_mgr == "homebrew"
  homebrew:
    name:
      - git
      - hub
    state: present
- name: gitconfig
  template:
    src: gitconfig
    dest: ~/.gitconfig
    mode: 0600
- name: global gitignore
  copy:
    src: gitignore
    dest: ~/.gitignore
    mode: 0600
