---
- name: Install git and hub
  become: "{{'no' if ansible_pkg_mgr == 'homebrew' else 'yes'}}"
  package:
    name: '{{item}}'
    state: present
  loop:
  - git
  - hub
- name: gitconfig
  template:
    src: gitconfig
    dest: ~/.gitconfig
    mode: 0600
- name: global gitignore
  copy:
    src: gitignore
    dest: ~/.gitignore
    mode: 0600
