---
- name: Install Java
  homebrew_cask:
    name: java
    state: present
- name: Install Maven
  homebrew:
    name: maven
    state: present
- name: Install google-java-format
  homebrew:
    name: google-java-format
    state: present
