---
- name: apt-get openjdk-8
  become: yes
  when: ansible_pkg_mgr == "apt"
  apt:
    name: openjdk-8-jdk
    state: present
- name: homebrew java
  when: ansible_pkg_mgr == "homebrew"
  homebrew_cask:
    name: java
    state: present
- pacman:
    name: jdk8-openjdk
    state: present
  when: ansible_pkg_mgr == "pacman"
  become: yes
