---
- name: create the zfs filesystem that will serve as the share point
  zfs:
    name: zroot/data
    state: present
    extra_zfs_properties:
      mountpoint: "/data"

- name: set data owner to nobody
  file:
    path: '/data'
    mode: '755'
    state: directory
    owner: nobody
    group: nogroup

- name: configure /etc/exports based on the template
  template:
    src: exports
    dest: /etc/exports
  register: exportsfile

- name: enable the rpcbind service at boot time
  sysrc:
    name: rpcbind_enable
    value: "YES"

- name: enable the nfs server at boot time
  sysrc:
    name: nfs_server_enable
    value: "YES"

- name: enable servicing of rpc requests for regular files
  sysrc:
    name: mountd_flags
    value: "-r"

- name: ensure nfs server is running
  service:
    name: nfsd
    state: started

- name: restart nfsd if the /etc/exports has changed
  when: exportsfile.changed
  service:
    name: nfsd
    state: restarted
