---
- package:
    state: present
    name:
      - ctop
      - htop
      - nmap
      - pandoc
      - qemu
      - shellcheck
      - sqlite
      - tree
      - curl
      - nnn
  become: "{{'no' if ansible_pkg_mgr == 'homebrew' else 'yes'}}"
