---
- name: Install Docker
  homebrew_cask:
    name: docker
    state: present

- name: Install ctop
  homebrew:
    name: ctop
    state: present

- name: Install Kubernetes CLI
  homebrew:
    name: kubernetes-cli
    state: present
