---
- include_tasks: darwin.yml
  when: ansible_os_family == "Darwin"
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"
- include_tasks: arch.yml
  when: ansible_os_family == "Archlinux"
