---
- name: Install jq
  package:
    name: jq
    state: present
  become: "{{'no' if ansible_pkg_mgr == 'homebrew' else 'yes'}}"
- name: jq directory
  file:
    path: '~/.jq'
    state: directory
    mode: '700'
- name: jq library
  copy:
    src: '{{item}}'
    dest: '~/.jq/{{item}}'
  loop:
    - aws.jq
