---
- homebrew_cask:
    name: gimp
    state: present
  when: ansible_pkg_mgr == "homebrew"
- apt:
    name: gimp
    state: present
  when: ansible_pkg_mgr == "apt"
  become: yes
- pacman:
    name: gimp
    state: present
  when: ansible_pkg_mgr == "pacman"
  become: yes
