---
- package:
    name: newsboat
    state: present
  become: "{{'no' if ansible_pkg_mgr == 'homebrew' else 'yes'}}"
- file:
    path: ~/.newsboat
    state: directory
    mode: 0700
- template:
    src: urls
    dest: ~/.newsboat/urls
    mode: 0600
