---
- when: ansible_pkg_mgr == "apt"
  become: true
  apt:
    name: postgresql-client
    state: present
- when: ansible_pkg_mgr == "pacman"
  become: true
  pacman:
    name: postgresql-libs
    state: present
- when: ansible_pkg_mgr == "homebrew"
  homebrew:
    name: "postgresql@9.5"
    state: present
- template:
    src: pgpass.j2
    dest: '~/.pgpass'
    mode: '600'

