---
- name: install ssh server
  become: yes
  when: ansible_facts['os_family'] == 'Debian'
  apt:
    name: openssh-server
    state: present
- name: ensure ssh server is running
  when: ansible_facts['os_family'] == 'Debian'
  become: yes
  systemd:
    name: sshd
    state: started
    enabled: yes
- name: ensure .ssh directory exists
  file:
    path: ~/.ssh
    state: directory
    mode: '700'
- name: update authorized keys
  copy:
    src: authorized_keys
    dest: ~/.ssh/authorized_keys
